### ISSUE TITLE
Wormelde-Spam möglich

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#10]
Es ist in einer Debatte möglich, mehrere Wortmeldungen direkt hintereinander abzugeben. Das scheint in einer Debatte etwas komisch.

Zum einen ist es möglich, mehrmals die Liste mit Wortmeldungen voll zu spammen. 

Derjenige der sich gemeldet hat hat sich ja schon gemeldet. Warum sollte er sich direkt noch mehr Meldeplätze "reservieren" wollen?

Sollte Pro Nutzer nicht nur eine offene Meldung möglich sein?

**Comment by Lumean97** [comment]
Guter Vorschlag. Setze ich um. Gleichzeitig muss ich dem Nutzer dann noch die Möglichkeit geben seine Wortmeldung bearbeiten zu können, oder nicht? Oder löschen zu können wohl eher
