### ISSUE TITLE
Kein Zurück mehr aus Erstellter Debatte

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#11]
Sobald ich eine Debatte erstellt und geöffnet habe, ist es mir nicht mehr möglich die Debatte zu verlassen und z.B. auf die Beitreten Seite der App zu gelangen. Der "Zurück" Button schmeißt einen darüber hinaus aus der App. Somit ist der Host der Debatte verloren.

**Comment by Lumean97** [comment]
Ist gewollt. Ist die Debatte erstellt soll diese so lange laufen bis sie zu ende ist. Einfach raustappen sollte er nicht.
