### ISSUE TITLE
App startet bei "Zurück Button" neu

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#13]
Wenn ich auf der Startseite "Beitreten" oder auf der Erstellenseite bin und auf den Zurück Button klicke, dann wird die App in den Hintergrund verschoben. Sobald ich aber über das Tab Menü die App wieder aufrufe, wird diese neu gestartet und man landet wieder auf der Startseite "Beitreten".

**Comment by Lumean97** [comment]
Ist korrekt so. Das ist eine Tabview. Das einzige was ich machen kann ist auf dieser View den Back Button zu catchen und nur die App zu schließen, wenn ich auf dem Beitreten Tab bin. Was meinst du?

**Comment by GurkenKater** [comment]
Das klingt nach einer besseren Lösung als bis jetzt, ja wäre doch ok.
