### ISSUE TITLE
Merkmale hinzufügen schlecht erkennbar

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#5]
Beim Erstellen einer neuen Debatte habe ich zuerst einen Titel eingegeben und dann auf erstellen geklickt. Ich hatte erwartet das ich zu einer weiteren Seite komme, wo ich die Merkmale, welche ich vom Nutzer haben möchte, bestimmen kann. Dann war aber die Debatte schon erstellt.

Erst beim zweiten Mal probieren habe ich dann auf gut Glück auf das Plus unter dem Eingabefeld für den Debatten Titel geklickt. Dadurch hat sich dann erst die Konfiguration für die Merkmale geöffnet. 

Die Seite, welche für die Merkmal-Konfiguration geöffnet wird, könnte z.B. direkt unter das Eingabefeld für den Titel angebracht werden. Mit dem unscheinbaren Plus-Button kommt man nicht auf die Idee, dort das zu finden.

Jemand der die App nicht kennt wird vermutlich für eine längere Zeit nicht wissen, das es diese Option gibt.

**Comment by Lumean97** [comment]
Das mit der Seite unter dem Titel ist schwierig. Damit wären Mehrere Eigenschaften nicht möglich. Ich hätte 4 Vorschläge:
1. Es ist nicht möglich eine Debatte mit Zusatzmerkmalen zu erstellen (Würde sinn machen, unsere App ist ja für Quotierte Redelisten. Dementsprechend macht es keinen Sinn eine Redeliste ohne Eigenschaften zu erstellen). Beim Klick auf erstellen ohne Zusatzmerkmale ploppt ein Toast auf mit ner Warnmeldung, dass Eigenschaften noch nicht gesetzt wurden. Der Plus Button würde eine Rote Farbe erhalten, um das zu verdeutlichen.

2. Wir erlauben es keine Merkmale zu bestimmen. Beim erstellen erhält man einen Warn Dialog, ob man wirklich eine Debatte ohne Eigenschaften erstellen will.
3. Statt einem Plus Icon bekommt der Button einen Text wie "Eigenschaft hinzufügen"
4. Tutorial welches beim erstmaligen zeigen der Erstellen Seite aufploppt und kurz jeden Button erklärt

**Comment by Lumean97** [comment]
![image](https://user-images.githubusercontent.com/11708668/59843297-8dfbb800-9358-11e9-9207-e94e4fa97bd2.png)
Zu 1. : So könnte das dann aussehen

**Comment by GurkenKater** [comment]
Intuitiv hätte ich einen Button mit der Aufschrift "Merkmal hinzufügen" erwartet. Also Punkt 3.

**Comment by Lumean97** [comment]
![image](https://user-images.githubusercontent.com/11708668/59868687-d4b9d400-9391-11e9-82a8-4f60646089eb.png)
Ich habe mal eine Mischung genommen. Passt das?
