### ISSUE TITLE
Merkmale lassen sich nicht löschen.

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#7]
Beim Erstellen einer neuen Debatte wird beim Hinzufügen eines Merkmales eine Liste unten auf der Erstellungseite mit dem jeweiligen Merkmal befüllt. Es ist mir bisher aber nicht möglich gewesen, doch wieder ein Merkmal doch zu löschen. Man kann es lediglich nochmal anklicken um es zu bearbeiten. Eine Löschfunktion habe ich allerdings nicht gefunden.

Wie in #6 beschrieben, ist von default das Geschlecht als Merkmal hinterlegt. Dieses lässt sich zum Beispiel nicht löschen, braucht man die Angabe dieses Merkmales eventuel doch nicht.

**Comment by Lumean97** [comment]
737019bf0696ba1b1484fb55ffe14e565d176a4b fixed
