### ISSUE TITLE
Wahl bei Einzelauswahl wird mit Topic betitelt

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#8]
Beim Auswählen von Einzelauswahl bei der Erstellung von Merkmaldefinitionen erscheint ein Eingabefeld mit "Topic" als Placeholder. Unter Topic würde ich nicht erwarten das ich hier eine Einzelauswahlmöglichkeit eingeben soll.

Vielleicht wäre zum Beispiel "Wahloption" ein besserer Placeholder dafür?

**Comment by Lumean97** [comment]
Wäre eine Möglichkeit, kann ich einbauen. Ist kein Aufwand
