### ISSUE TITLE
Anklicken einer Wortmeldung bringt nichts

### ISSUE THREAD

**Issue by GurkenKater** [marcelherd/MOP-Quotify#9]
In der Liste mit den aktuellen Wortmeldungen kann man einzelne Wortmeldungen aklicken. Man bekommt eine Response in Form einer Animation. Aber das Anklicken führt keine Aktion aus.

Kann die Möglichkeit des Anklickens entfernt werden?

**Comment by Lumean97** [comment]
Ich schau mir gleich mal an ob das Anklicken entfernt werden kann. Ist glaube ich nur für den Debattenführer Wichtig um diese Wortmeldung auszuwählen.
